//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects,
//

import UIKit

// MARK: - View State
protocol ___VARIABLE_productName___ModelStateProtocol {

}

// MARK: - Intent Actions
protocol ___VARIABLE_productName___ModelActionsProtocol: AnyObject {

}

// MARK: - Route
protocol ___VARIABLE_productName___ModelRouterProtocol: AnyObject {
    
}
