//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the MVI Xcode Templates so
//  you can apply MVI architecture to your iOS and Mac projects,
//

import SwiftUI
import Combine


final class ___VARIABLE_productName___Model: ObservableObject, ___VARIABLE_productName___ModelStateProtocol {

}

// MARK: - Actions Protocol

extension ___VARIABLE_productName___Model: ___VARIABLE_productName___ModelActionsProtocol {

}

// MARK: - Route Protocol

extension ___VARIABLE_productName___Model: ___VARIABLE_productName___ModelRouterProtocol {

}
